---
- hosts: all
  become: true
#  become_user: root
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
    - "{{ VARIABLE_FILE }}"
    - "{{BASE_FILE_PATH}}globals.yml"

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:

    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install python-pip
      apt:
        name: python-pip
        state: latest

    - name: upgrade pip
      command: pip install --upgrade pip

    - name: install python-tackerclient
      pip:
        name: python-tackerclient

    - name: Install parted
      apt:
        name: parted
        state: latest

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-dev
        - libffi-dev
        - gcc
        - libssl-dev
        - python-selinux
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - libltdl7

    - name: Install git
      apt:
        name: git
        update_cache: yes
        state: latest


    - name: Clone git
      git:
        repo: https://github.com/openstack/kolla-ansible.git
        version: "{{ GIT_BRANCH }}"
        dest: "{{ GIT_CLONE_PATH_QUEENS }}"


    - name: switch to queens branch
      command: git checkout "{{ GIT_BRANCH }}"
      args:
       chdir: "{{ GIT_CLONE_PATH_QUEENS }}"
      when: (KOLLA_ANSIBLE_TAG is undefined) or (KOLLA_ANSIBLE_TAG is none) or (KOLLA_ANSIBLE_TAG | trim == '')

    - name: switch to queens branch via tag
      command: "git checkout tags/{{ KOLLA_ANSIBLE_TAG }}"
      args:
       chdir: "{{ GIT_CLONE_PATH_QUEENS }}"
      when: not((KOLLA_ANSIBLE_TAG is undefined) or (KOLLA_ANSIBLE_TAG is none) or (KOLLA_ANSIBLE_TAG | trim == ''))
    - name: install requirements
      pip:
        requirements: "{{ REQUIREMENT_KOLLA_ANSIBLE }}"

    - name: run setup.py
      command: python setup.py install
      args:
       chdir: "{{ GIT_CLONE_PATH_QUEENS }}"


    - name: apt-get update again
      apt:
        update_cache: yes

    - name: run start-registry command
      command: docker run -d -p 4000:5000 --restart=always --name registry  registry:2
      ignore_errors: True

    - name: replace data in init-runonce script
      replace:
        dest: '/etc/OpenStack/kolla-ansible/tools/init-runonce'
        regexp: '^(.*)neutron subnet-create --name 1-subnet --allocation-pool start=172.19.27.250,end=172.19.27.230 public1 172.19.27.0/24 --gateway 172.19.27.1(.*)$'
        replace: 'neutron subnet-create --name 1-subnet --allocation-pool start={{START_IP}},end={{END_IP}} public1 {{EXT_SUB}} --gateway {{EXT_GW}}'

    - lineinfile:
       destfile: '/etc/OpenStack/kolla-ansible/tools/init-runonce'
       state: absent
       regexp:  '(.*)neutron net-create demo-net --provider:network_type vxlan(.*)$'
    - lineinfile:
       destfile: '/etc/OpenStack/kolla-ansible/tools/init-runonce'
       state: absent
       regexp:  '(.*)neutron subnet-create demo-net 10.0.0.0/24 --name demo-subnet --gateway 10.0.0.1 --dns-nameservers list=true 8.8.8.8(.*)$'

    - lineinfile:
       destfile: '/etc/OpenStack/kolla-ansible/tools/init-runonce'
       state: absent
       regexp:  '(.*)neutron router-interface-add demo-router demo-subnet(.*)$'

    - lineinfile:
       destfile: '/etc/OpenStack/kolla-ansible/tools/init-runonce'
       line: 'openstack role add --project admin --user admin heat_stack_owner'
       insertbefore: 'cat << EOF'

    - name: makenode command
      when: enable_cinder == "yes"
      command: mknod /dev/loop2 b 7 2
      ignore_errors: True
    - name: create physical disk for cinder
      when: enable_cinder == "yes"
      command: "dd if=/dev/zero of=/var/lib/cinder_data.img bs={{BASE_SIZE}} count={{COUNT}}"
    - name: losesetup command
      when: enable_cinder == "yes"
      command: losetup  /dev/loop2 /var/lib/cinder_data.img
      ignore_errors: True
    - name: pvcreate command
      when: enable_cinder == "yes"
      command: pvcreate /dev/loop2
    - name: vgcreate command
      command: vgcreate cinder-volumes /dev/loop2
      when: enable_cinder == "yes"
    - name: prepare ceph OSD drive
      when: enable_ceph == "yes"
      command: "parted {{ item }} -s -- mklabel gpt mkpart KOLLA_CEPH_OSD_BOOTSTRAP 1 -1"
#      ignore_errors: True
      with_items:
        "{{SECOND_STORAGE}}"
    - name: "Creating directory /etc/kolla/config"
      when: enable_ceph == "yes"
      file:
        dest: /etc/kolla/config
        state: directory
    - name: Copy ceph.conf
      when: enable_ceph == "yes"
      copy:
       src: "{{BASE_FILE_PATH}}ceph.conf"
       dest: "/etc/kolla/config/ceph.conf"

    - name: Copying Docker package file in /home/ubuntu
      copy:
       src: "{{BASE_FILE_PATH}}docker-engine_17.05.0-ce-0-ubuntu-xenial_amd64.deb"
       dest: "{{ DOCKER_LIST_DEST }}"

    - name: dpkgi -i docker-engine=17.05~xenial
      command: dpkg -i "{{ DOCKER_LIST_DEST }}"


    - name: apt-get update again
      apt:
        update_cache: yes


    - name: Make directory docker.service.d
      file:
       dest: /etc/systemd/system/docker.service.d
       state: directory

    - name: Copy http-proxy.conf in the docker.service.d directory
      copy:
       src: "{{BASE_FILE_PATH}}http-proxy_bak.conf"
       dest: "{{ HTTP_PROXY_DEST }}"



    - name: replace data in http-proxy.conf
      lineinfile:
        dest: "{{ HTTP_PROXY_DEST }}"
        regexp: 'Environment="HTTP_PROXY="'
        line: 'Environment="HTTP_PROXY={{ http_proxy }}"'

    - name: Copy kolla.conf in the docker.service.d directory
      when: GIT_BRANCH == "stable/queens"
      copy:
       src: "{{BASE_FILE_PATH}}kolla.conf"
       dest: "{{ KOLLA_CONF_DEST }}"

    - name: Install ansible
      pip:
       name: ansible
       version: 2.2.2.0

    - name: load uio_pci_generic kernel module
      shell: modprobe uio_pci_generic
      ignore_errors: True
      when: enable_ovs_dpdk == "yes"
    - name: load vfio_pci kernel module
      shell: modprobe vfio_pci
      ignore_errors: True
      when: enable_ovs_dpdk == "yes"

    - name: add line to /etc/modules
      lineinfile:
       dest: /etc/modules
       line: 'uio_pci_generic'
      when: enable_ovs_dpdk == "yes"
    - name: add line to /etc/modules
      lineinfile:
       dest: /etc/modules
       line: 'vfio_pci'
      when: enable_ovs_dpdk == "yes"
    - name: Install ansible for dpdk
      pip:
       name: ansible
       version: 2.3.1.0
      when: enable_ovs_dpdk == "yes"
    - name: Copy ml2_conf.ini
      copy:
       src: "{{BASE_FILE_PATH}}ml2_conf.ini"
       dest: "/etc/kolla/config/neutron/ml2_conf.ini"
      when : enable_ovs_dpdk == "yes"

    - name:  insert docker_opts in docker
      lineinfile:
        dest: "{{ DEFAULT_DOCKER_FILE }}"
        regexp: '^(.*)#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"(.*)$'
        line: 'DOCKER_OPTS= "{{ DOCKER_OPTS }}"'


    - name: copy the file
      command: cp "{{ DOCKER_SERVICE_SRC }}" "{{ DOCKER_SERVICE_DEST }}"

    - name: append data in docker.service
      lineinfile:
        dest: "{{ DOCKER_SERVICE_DEST }}"
        line: "EnvironmentFile=-/etc/default/docker \nMountFlags=shared"
        insertafter: '^\[Service\]'
        state: present

    - name: replace data in docker.service
      lineinfile:
        dest: "{{ DOCKER_SERVICE_DEST }}"
        regexp: 'ExecStart=/usr/bin/dockerd -H fd://'
        line: "ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS"

    - name: changes in docker  http-proxy file
      lineinfile:
        dest: "{{ HTTP_PROXY_DEST }}"
        regexp: 'Environment="HTTP_PROXY={{ http_proxy }}"'
        line: 'Environment="HTTP_PROXY={{ http_proxy }}" "NO_PROXY=localhost,{{ no_proxy }}"'


    - name: copy daemon.json
      copy:
       src: "{{BASE_FILE_PATH}}daemon.json"
       dest: "{{ DAEMON_DOCKER_FILE_DEST }}"
      when: PULL_HUB != "yes"

    - name: systemctl daemon-reload
      command: systemctl daemon-reload

    - name: systemctl restart docker
      command: systemctl restart docker


    - name: add line to /etc/modules
      lineinfile:
       dest: /etc/modules
       line: 'configfs'
      when: enable_cinder == "yes"

    - name: update-initramfs
      command: update-initramfs -u
      ignore_errors: True
      when: enable_cinder == "yes"

    - name: systemctl stop open-iscsi
      command: systemctl stop open-iscsi
      when: enable_cinder == "yes"

    - name: systemctl disable open-iscsi
      command: systemctl disable open-iscsi
      when: enable_cinder == "yes"

    - name: systemctl stop iscsid
      command: systemctl stop iscsid
      when: enable_cinder == "yes"

    - name: systemctl disable iscsid
      command: systemctl disable iscsid
      when: enable_cinder == "yes"


    - name: Install ntp
      apt:
       name: ntp
       state: latest

    - name: Copy /etc/kolla folder
      command: cp -r /etc/OpenStack/kolla-ansible/etc/kolla/ /etc/

    - name: Copy contents of /usr/local/share/kolla/ansible/inventory/ to /etc/kolla_packages/source/
      copy:
       src: "{{BASE_FILE_PATH}}inventory"
       dest: "{{ INVENTORY_DEST }}"

    - name: Copy globals.yml in the /etc/kolla directory
      copy:
       src: "{{BASE_FILE_PATH}}globals.yml"
       dest: "{{ GLOBAL_FILE_DEST }}"

    - name: cleanup-dangling images
      shell: ./cleanup-images --dangling
      when: GIT_BRANCH == "stable/queens"
      args:
       chdir: /etc/OpenStack/kolla-ansible/tools
       executable: /bin/bash
      ignore_errors: True

    - name: Fetch docker repository tag
      shell: docker images | grep horizon | awk '{print $2}'
      register: tag
    - debug:
        var: tag


    - name: adding openstack release tag in globals.yaml
      lineinfile:
       dest: /etc/kolla/globals.yml
       line: 'openstack_release: "{{tag.stdout}}"'
       insertafter: '#openstack_release: "auto"'

    - name: kolla generate passwords
      command: kolla-genpwd


    - name: kolla ansible prechecks
      command: kolla-ansible prechecks  -i "{{ ALL_IN_ONE_FILE }}"

    - name: kolla ansible pull
      command: kolla-ansible pull  -i "{{ ALL_IN_ONE_FILE }}"

    - name: kolla ansible deploy
      command: kolla-ansible deploy  -i "{{ ALL_IN_ONE_FILE }}"

    - name: kolla ansible post deploy
      command: kolla-ansible post-deploy

    - name: Changing perm of "/etc/kolla/admin-openrc.sh", adding "+x"
      file: dest=/etc/kolla/admin-openrc.sh mode=a+x

    - name: Changing perm of "/usr/local/share/kolla-ansible/init-runonce.sh", adding "+x"
      file: dest=/usr/local/share/kolla-ansible/init-runonce mode=a+x


    - name: apt-get python-openstackclient
      command: apt-get -y install python-openstackclient

    - name: apt-get python-neutronclient
      command: apt-get -y install python-neutronclient

    - name: apt-get python-novaclient
      command: apt-get -y install python-novaclient

    - name: run admin-openrc script
      shell: source /etc/kolla/admin-openrc.sh  && chmod 777 /etc/OpenStack/kolla-ansible/tools/init-runonce && /etc/OpenStack/kolla-ansible/tools/init-runonce
      args:
       executable: /bin/bash

    - name: systemctl daemon-reload
      command: systemctl daemon-reload

    - name: systemctl restart docker
      command: systemctl restart docker

    - shell: ip a show {{ network_interface }} | grep inet | grep global | awk '{ print$2}'
      register: command_output


    - debug: msg="{{ command_output.stdout_lines[0]}}"

